name = "inko"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]
main = "src/main.ts"

[assets]
directory = "./public"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "inko-data"
database_id = "inko-data"

[[kv_namespaces]]
binding = "KV"
id = "inko-settings"

[[r2_buckets]]
binding = "R2"
bucket_name = "inko-files"

[limits]
cpu_ms = 1000
