name = "htmx-hono-cf-starter"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "src/main.ts"

[assets]
directory = "./public"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "inko-data"
database_id = "inko-data"
